version: "3.8"
services:
  active-directory:
    image: v2okimochi/samba-ad-local:1.0.0
    container_name: v2okimochi-ad-local
    privileged: true
    environment:
      DOMAIN: V2-OKIMOCHI
      REALM: v2-okimochi.local
      ADMIN_PASSWORD: password_1
      DNS_BACKEND: SAMBA_INTERNAL
      SAMPLE_USER_NAME: dev
      SAMPLE_USER_PASSWORD: dev
    ports:
      - 389:389

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    container_name: v2okimochi-ldap-local-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8282:80"
    links:
      - "active-directory:ldap"
